services:
  - type: web
    name: nse-market-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NSE_ARCHIVE_DIR
        value: ""
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        value: MoengaAlex1/nse_predictor
    healthCheckPath: /
    autoDeploy: true
